name: build-scarfacefix

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-win32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: >-
            mingw-w64-i686-gcc
            make

      - name: Build DLL
        shell: msys2 {0}
        run: |
          gcc -m32 -O2 -s -shared -o ScarfaceFix.dll ScarfaceFix.cpp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScarfaceFix-dll
          path: ScarfaceFix.dll
