name: build-scarfacefix

on:
  workflow_dispatch:

jobs:
  build-win32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: |
            mingw-w64-i686-gcc
            make

      - name: Build ScarfaceFix.dll
        run: |
          echo "Starting GCC build"
          C:\msys64\mingw32\bin\gcc.exe -m32 -O2 -s -shared -o ScarfaceFix.dll ScarfaceFix.cpp
          echo "Build finished"
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScarfaceFix-dll
          path: ScarfaceFix.dll
